workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
      vars:
        ANDROID_KEYSTORE: Encrypted(your_encrypted_keystore)
        ANDROID_KEYSTORE_PASSWORD: Encrypted(your_encrypted_keystore_password)
        ANDROID_KEY_ALIAS: Encrypted(your_encrypted_key_alias)
        ANDROID_KEY_PASSWORD: Encrypted(your_encrypted_key_password)
    scripts:
      - name: Print environment variables
        script: |
          echo "ANDROID_KEYSTORE: ${#ANDROID_KEYSTORE}"
          echo "ANDROID_KEYSTORE_PASSWORD: ${#ANDROID_KEYSTORE_PASSWORD}"
          echo "ANDROID_KEY_ALIAS: ${#ANDROID_KEY_ALIAS}"
          echo "ANDROID_KEY_PASSWORD: ${#ANDROID_KEY_PASSWORD}"
      - name: Build Android app bundle
        script: |
          echo "Building Android app bundle..."
          flutter build appbundle --release --flavor android-production -t lib/main_prod.dart
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        KEYCHAIN_PASSWORD: Rehan@734266479
        CERTIFICATE_PASSWORD: Rehan@734266479
    scripts:
      - name: Print environment variables
        script: |
          echo "KEYCHAIN_PASSWORD: ${#KEYCHAIN_PASSWORD}"
          echo "CERTIFICATE_PASSWORD: ${#CERTIFICATE_PASSWORD}"
      - name: Set up keychain and add certificates
        script: |
          echo "Initializing keychain..."
          security create-keychain -p $KEYCHAIN_PASSWORD /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain
          security default-keychain -s /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain
          security unlock-keychain -p $KEYCHAIN_PASSWORD /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain
          security set-keychain-settings -lut 21600 /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain

          echo "Checking if certificate file exists..."
          if [ -f /Users/builder/Library/MobileDevice/Certificates/tmpkle4ws46.p12 ]; then
            echo "Certificate file found."
          else
            echo "Certificate file not found!"
            exit 1
          fi

          echo "Importing certificates..."
          security import /Users/builder/Library/MobileDevice/Certificates/tmpkle4ws46.p12 -k /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign || (echo "Failed to import certificate" && exit 1)

      - name: Build and code sign
        script: |
          echo "Building and signing the iOS app..."
          flutter build ios --release --flavor ios-production -t lib/main_prod.dart

          echo "Archiving the app..."
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $HOME/build/Runner.xcarchive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="iPhone Distribution: 57MY2GPC32" \
            PROVISIONING_PROFILE_SPECIFIER="DentalKeyDistribute"

          echo "Exporting the archive to an IPA..."
          xcodebuild -exportArchive \
            -archivePath $HOME/build/Runner.xcarchive \
            -exportPath $HOME/build \
            -exportOptionsPlist ios/ExportOptions.plist

      - name: Build artifact
        script: |
          echo "Moving the generated IPA file..."
          mv $HOME/build/Runner.ipa $HOME/build/ios/Runner.ipa

    artifacts:
      - build/ios/Runner.ipa

  web-workflow:
    name: Web Workflow
    environment:
      flutter: stable
    scripts:
      - name: Set up build
        script: |
          echo "Starting Web build..."
      - name: Build Web app
        script: |
          flutter build web --release
    artifacts:
      - build/web
