workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        KEYCHAIN_PASSWORD: Rehan@734266479
        CERTIFICATE_PASSWORD: Rehan@734266479
    scripts:
      - name: Debug Environment Variables
        script: |
          echo "Keychain Password: $KEYCHAIN_PASSWORD"
          echo "Certificate Password: $CERTIFICATE_PASSWORD"
      - name: Set up keychain and add certificates
        script: |
          echo "Initializing keychain..."
          security create-keychain -p $KEYCHAIN_PASSWORD /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain
          security default-keychain -s /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain
          security unlock-keychain -p $KEYCHAIN_PASSWORD /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain
          security set-keychain-settings -lut 21600 /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain

          echo "Importing certificates..."
          security import /Users/builder/Library/MobileDevice/Certificates/tmpflazh9j7.p12 -k /Users/builder/Library/codemagic-cli-tools/keychains/build.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
      - name: Build and code sign
        script: |
          # Build the iOS app
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
